set(headers
	BSCollision.h
	BSGeometry.h
	BSGraphics.h
	BSLight.h
	BSModelDB.h
	BSParticleShaderEmitter.h
	BSSkin.h
	CustomMenu.h
	GameAPI.h
	GameCamera.h
	GameCustomization.h
	GameData.h
	GameEvents.h
	GameExtraData.h
	GameFormComponents.h
	GameForms.h
	GameHandle.h
	GameInput.h
	GameMemory.h
	GameMenus.h
	GameMessages.h
	GameObjects.h
	GameRTTI.h
	GameRTTI.inl
	GameReferences.h
	GameSettings.h
	GameStreams.h
	GameThreads.h
	GameTypes.h
	GameUtilities.h
	GameWorkshop.h
	Hooks_Camera.h
	Hooks_Debug.h
	Hooks_GameData.h
	Hooks_Gameplay.h
	Hooks_Input.h
	Hooks_Memory.h
	Hooks_ObScript.h
	Hooks_Papyrus.h
	Hooks_SaveLoad.h
	Hooks_Scaleform.h
	Hooks_Threads.h
	InputMap.h
	InternalSerialization.h
	NiCloningProcess.h
	NiExtraData.h
	NiMaterials.h
	NiNodes.h
	NiObjects.h
	NiProperties.h
	NiRTTI.h
	NiSerialization.h
	NiTextures.h
	NiTypes.h
	ObScript.h
	PapyrusActor.h
	PapyrusActorBase.h
	PapyrusArgs.h
	PapyrusArmor.h
	PapyrusArmorAddon.h
	PapyrusCell.h
	PapyrusComponent.h
	PapyrusConstructibleObject.h
	PapyrusDefaultObject.h
	PapyrusDelayFunctors.h
	PapyrusDelayFunctorsDef.inl
	PapyrusDelayFunctorsDef_Base.inl
	PapyrusEncounterZone.h
	PapyrusEquipSlot.h
	PapyrusEvents.h
	PapyrusEventsDef.inl
	PapyrusEventsDef_Base.inl
	PapyrusF4SE.h
	PapyrusFavoritesManager.h
	PapyrusForm.h
	PapyrusGame.h
	PapyrusHeadPart.h
	PapyrusInput.h
	PapyrusInstanceData.h
	PapyrusInterfaces.h
	PapyrusLocation.h
	PapyrusMaterialSwap.h
	PapyrusMath.h
	PapyrusMiscObject.h
	PapyrusNativeFunctionDef.inl
	PapyrusNativeFunctionDef_Base.inl
	PapyrusNativeFunctions.h
	PapyrusObjectMod.h
	PapyrusObjectReference.h
	PapyrusObjects.h
	PapyrusPerk.h
	PapyrusScaleformAdapter.h
	PapyrusScriptObject.h
	PapyrusSerialization.h
	PapyrusStruct.h
	PapyrusUI.h
	PapyrusUtilities.h
	PapyrusUtility.h
	PapyrusVM.h
	PapyrusValue.h
	PapyrusWaterType.h
	PapyrusWeapon.h
	PluginAPI.h
	PluginManager.h
	ScaleformAPI.h
	ScaleformCallbacks.h
	ScaleformLoader.h
	ScaleformMovie.h
	ScaleformSerialization.h
	ScaleformState.h
	ScaleformTranslator.h
	ScaleformTypes.h
	ScaleformValue.h
	Serialization.h
	Translation.h
	bhkWorld.h
)
