set(sources
	BSCollision.cpp
	BSGeometry.cpp
	BSGraphics.cpp
	BSLight.cpp
	BSModelDB.cpp
	BSParticleShaderEmitter.cpp
	BSSkin.cpp
	CustomMenu.cpp
	GameAPI.cpp
	GameCamera.cpp
	GameCustomization.cpp
	GameData.cpp
	GameEvents.cpp
	GameExtraData.cpp
	GameFormComponents.cpp
	GameForms.cpp
	GameHandle.cpp
	GameInput.cpp
	GameMemory.cpp
	GameMenus.cpp
	GameMessages.cpp
	GameObjects.cpp
	GameRTTI.cpp
	GameReferences.cpp
	GameSettings.cpp
	GameStreams.cpp
	GameThreads.cpp
	GameTypes.cpp
	GameUtilities.cpp
	GameWorkshop.cpp
	Hooks_Camera.cpp
	Hooks_Debug.cpp
	Hooks_GameData.cpp
	Hooks_Gameplay.cpp
	Hooks_Input.cpp
	Hooks_Memory.cpp
	Hooks_ObScript.cpp
	Hooks_Papyrus.cpp
	Hooks_SaveLoad.cpp
	Hooks_Scaleform.cpp
	Hooks_Threads.cpp
	InputMap.cpp
	InternalSerialization.cpp
	NiExtraData.cpp
	NiMaterials.cpp
	NiNodes.cpp
	NiObjects.cpp
	NiProperties.cpp
	NiRTTI.cpp
	NiSerialization.cpp
	NiTextures.cpp
	NiTypes.cpp
	ObScript.cpp
	PapyrusActor.cpp
	PapyrusActorBase.cpp
	PapyrusArgs.cpp
	PapyrusArmor.cpp
	PapyrusArmorAddon.cpp
	PapyrusCell.cpp
	PapyrusComponent.cpp
	PapyrusConstructibleObject.cpp
	PapyrusDefaultObject.cpp
	PapyrusDelayFunctors.cpp
	PapyrusEncounterZone.cpp
	PapyrusEquipSlot.cpp
	PapyrusEvents.cpp
	PapyrusF4SE.cpp
	PapyrusFavoritesManager.cpp
	PapyrusForm.cpp
	PapyrusGame.cpp
	PapyrusHeadPart.cpp
	PapyrusInput.cpp
	PapyrusInstanceData.cpp
	PapyrusInterfaces.cpp
	PapyrusLocation.cpp
	PapyrusMaterialSwap.cpp
	PapyrusMath.cpp
	PapyrusMiscObject.cpp
	PapyrusNativeFunctions.cpp
	PapyrusObjectMod.cpp
	PapyrusObjectReference.cpp
	PapyrusObjects.cpp
	PapyrusPerk.cpp
	PapyrusScaleformAdapter.cpp
	PapyrusScriptObject.cpp
	PapyrusSerialization.cpp
	PapyrusStruct.cpp
	PapyrusUI.cpp
	PapyrusUtilities.cpp
	PapyrusUtility.cpp
	PapyrusVM.cpp
	PapyrusValue.cpp
	PapyrusWaterType.cpp
	PapyrusWeapon.cpp
	PluginManager.cpp
	ScaleformAPI.cpp
	ScaleformCallbacks.cpp
	ScaleformLoader.cpp
	ScaleformMovie.cpp
	ScaleformSerialization.cpp
	ScaleformState.cpp
	ScaleformTranslator.cpp
	ScaleformTypes.cpp
	ScaleformValue.cpp
	Serialization.cpp
	Translation.cpp
	bhkWorld.cpp
	f4se.cpp
)
